const PDFDocument = require('pdfkit');

const generateProjectPDF = (project) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const BLUE = '#2563EB';
      const DARK = '#1E293B';
      const GRAY = '#64748B';
      const LIGHT_BG = '#F8FAFC';

      // Header
      doc.rect(0, 0, doc.page.width, 100).fill(BLUE);
      doc.fill('white').fontSize(24).font('Helvetica-Bold').text('ProjectGen', 50, 25);
      doc.fontSize(12).font('Helvetica').text('Final Year Project Report', 50, 55);
      doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 50, 72);

      doc.moveDown(3);
      doc.fill(DARK);

      // Title
      doc.fontSize(18).font('Helvetica-Bold').fill(BLUE).text(project.title, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').fill(GRAY)
        .text(`${project.stream} | ${project.domain} | ${project.technology} | ${project.difficulty}`, { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(BLUE);
      doc.moveDown(1);

      const sectionTitle = (text) => {
        doc.moveDown(0.8);
        doc.rect(50, doc.y, 495, 22).fill(BLUE);
        doc.fill('white').fontSize(12).font('Helvetica-Bold').text(text, 58, doc.y - 18);
        doc.fill(DARK).moveDown(0.6);
      };

      const bodyText = (text) => {
        doc.fontSize(10).font('Helvetica').fill(DARK).text(text, { align: 'justify' });
        doc.moveDown(0.5);
      };

      // Abstract
      sectionTitle('1. Abstract');
      bodyText(project.abstract);

      // Problem Statement
      sectionTitle('2. Problem Statement');
      bodyText(project.problemStatement);

      // Objectives
      sectionTitle('3. Objectives');
      project.objectives.forEach((obj, i) => {
        doc.fontSize(10).font('Helvetica').fill(DARK).text(`${i + 1}. ${obj}`);
      });
      doc.moveDown(0.5);

      // Modules
      sectionTitle('4. System Modules');
      project.modules.forEach((mod) => {
        doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text(`• ${mod.name}`);
        doc.fontSize(10).font('Helvetica').fill(DARK).text(`  ${mod.description}`);
        doc.moveDown(0.3);
      });

      // Technology Stack
      sectionTitle('5. Technology Stack');
      const ts = project.technologyStack;
      const tsRows = [
        ['Frontend', (ts.frontend || []).join(', ')],
        ['Backend', (ts.backend || []).join(', ')],
        ['Database', (ts.database || []).join(', ')],
        ['Tools & DevOps', (ts.tools || []).join(', ')]
      ];
      tsRows.forEach(([label, value]) => {
        doc.fontSize(10).font('Helvetica-Bold').fill(DARK).text(`${label}: `, { continued: true });
        doc.font('Helvetica').fill(GRAY).text(value);
        doc.moveDown(0.3);
      });

      // Methodology
      sectionTitle('6. Methodology');
      bodyText(project.methodology);

      // System Architecture
      sectionTitle('7. System Architecture');
      bodyText(project.systemArchitecture);

      // Flow Diagram Description
      sectionTitle('8. Flow Diagram');
      bodyText(project.flowDiagramDescription);

      // Future Scope
      sectionTitle('9. Future Scope');
      project.futureScope.forEach((scope, i) => {
        doc.fontSize(10).font('Helvetica').fill(DARK).text(`${i + 1}. ${scope}`);
      });
      doc.moveDown(0.5);

      // Conclusion
      sectionTitle('10. Conclusion');
      bodyText(project.conclusion);

      // Footer
      doc.moveDown(2);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(GRAY);
      doc.moveDown(0.5);
      doc.fontSize(9).fill(GRAY).text('Generated by ProjectGen — Final Year Project Generator for Students', { align: 'center' });
      doc.text('© 2026 ProjectGen. All rights reserved.', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

const generatePPTOutline = (project) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const BLUE = '#2563EB';
      const DARK = '#1E293B';

      const slide = (number, title, content) => {
        if (number > 1) doc.addPage();
        doc.rect(0, 0, doc.page.width, 70).fill(BLUE);
        doc.fill('white').fontSize(10).font('Helvetica').text(`Slide ${number}`, 50, 15);
        doc.fontSize(16).font('Helvetica-Bold').text(title, 50, 30);
        doc.fill(DARK).moveDown(3);
        doc.fontSize(11).font('Helvetica');
        content.forEach((line) => {
          doc.text(`• ${line}`);
          doc.moveDown(0.4);
        });
      };

      slide(1, project.title, [
        `Stream: ${project.stream}`,
        `Domain: ${project.domain}`,
        `Technology: ${project.technology}`,
        `Difficulty: ${project.difficulty}`,
        `Presented by: [Your Name]`,
        `Academic Year: 2025-26`
      ]);
      slide(2, 'Introduction & Problem Statement', [project.problemStatement.substring(0, 300) + '...']);
      slide(3, 'Objectives', project.objectives);
      slide(4, 'System Modules', project.modules.map((m) => `${m.name}: ${m.description.substring(0, 80)}`));
      slide(5, 'Technology Stack', [
        `Frontend: ${project.technologyStack.frontend.join(', ')}`,
        `Backend: ${project.technologyStack.backend.join(', ')}`,
        `Database: ${project.technologyStack.database.join(', ')}`,
        `Tools: ${project.technologyStack.tools.join(', ')}`
      ]);
      slide(6, 'Methodology', project.methodology.split('\n').filter((l) => l.trim()).slice(0, 8));
      slide(7, 'System Architecture', project.systemArchitecture.split('\n').filter((l) => l.trim()).slice(0, 8));
      slide(8, 'Future Scope', project.futureScope);
      slide(9, 'Conclusion', [project.conclusion.substring(0, 400) + '...']);
      slide(10, 'Thank You', ['Questions & Answers', 'GitHub: github.com/yourproject', 'Guided by: [Guide Name]', 'ProjectGen — FYP Generator']);

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateProjectPDF, generatePPTOutline };
